/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        "on-background": "var(--on-background)",
        surface: "var(--surface)",
        "surface-dim": "var(--surface-dim)",
        "surface-bright": "var(--surface-bright)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-surface": "var(--on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "inverse-surface": "var(--inverse-surface)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "surface-tint": "var(--surface-tint)",
        outline: "var(--outline)",
        "outline-variant": "var(--outline-variant)",
        primary: "var(--primary)",
        "on-primary": "var(--on-primary)",
        "primary-container": "var(--primary-container)",
        "on-primary-container": "var(--on-primary-container)",
        "inverse-primary": "var(--inverse-primary)",
        "primary-fixed": "var(--primary-fixed)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        secondary: "var(--secondary)",
        "on-secondary": "var(--on-secondary)",
        "secondary-container": "var(--secondary-container)",
        "on-secondary-container": "var(--on-secondary-container)",
        "secondary-fixed": "var(--secondary-fixed)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        tertiary: "var(--tertiary)",
        "on-tertiary": "var(--on-tertiary)",
        "tertiary-container": "var(--tertiary-container)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        error: "var(--error)",
        "on-error": "var(--on-error)",
        "error-container": "var(--error-container)",
        "on-error-container": "var(--on-error-container)",
        "accent-green": "var(--accent-green)",
        "ai-violet": "var(--ai-violet)",

        // Shadcn tokens
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
      },
      fontFamily: {
        geist: ["var(--font-geist)", "sans-serif"],
        inter: ["var(--font-inter)", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "500" }],
        "label-mono": ["13px", { lineHeight: "18px", letterSpacing: "0", fontWeight: "400" }],
      },
      spacing: {
        base: "var(--spacing-base)",
        "unit-1": "var(--spacing-unit-1)",
        "unit-2": "var(--spacing-unit-2)",
        "unit-4": "var(--spacing-unit-4)",
        "unit-6": "var(--spacing-unit-6)",
        "unit-8": "var(--spacing-unit-8)",
        "unit-12": "var(--spacing-unit-12)",
        "unit-16": "var(--spacing-unit-16)",
        gutter: "var(--spacing-gutter)",
        "margin-mobile": "var(--spacing-margin-mobile)",
        "margin-desktop": "var(--spacing-margin-desktop)",
        "max-width": "var(--spacing-max-width)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        "surface-card": "0 0 0 1px #1E293B",
        "surface-card-hover": "0 0 0 1px #334155",
        "linear-glow": "0 0 20px rgba(124, 92, 255, 0.15)",
        "inner-highlight": "inset 0 1px 0 0 rgba(255, 255, 255, 0.2)",
      },
      backgroundImage: {
        "ai-spark": "linear-gradient(to right, var(--primary-fixed-dim), var(--secondary-fixed-dim))",
      },
      backdropBlur: {
        popover: "20px",
      },
      animation: {
        "fade-in": "fadeIn 0.2s ease-out",
        "slide-up": "slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        rotate: "rotate 4s linear infinite",
        flow: "flow 20s linear infinite",
        fadeInScale: "fadeInScale 0.5s ease-out forwards",
        'pulse-glow': 'pulse-glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'flow-down': 'flow-down 1.5s linear infinite',
        'data-stream': 'data-stream 2s linear infinite',
        'pulse-green': 'pulse-green 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-violet': 'pulse-violet 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        rotate: {
          "to": { transform: "rotate(360deg)" },
        },
        flow: {
          "to": { strokeDashoffset: "-100" },
        },
        fadeInScale: {
          "to": { opacity: "1", transform: "scale(1)" },
        },
        'pulse-glow': {
            '0%, 100%': { opacity: '1', boxShadow: '0 0 15px 2px rgba(124, 92, 255, 0.4)' },
            '50%': { opacity: '.7', boxShadow: '0 0 5px 0px rgba(124, 92, 255, 0.2)' },
        },
        'pulse-green': {
            '0%, 100%': { opacity: '1', boxShadow: '0 0 15px 2px rgba(0, 208, 132, 0.2)' },
            '50%': { opacity: '.7', boxShadow: '0 0 5px 0px rgba(0, 208, 132, 0.1)' },
        },
        'pulse-violet': {
            '0%, 100%': { opacity: '1', boxShadow: '0 0 15px 2px rgba(168, 85, 247, 0.4)' },
            '50%': { opacity: '.7', boxShadow: '0 0 5px 0px rgba(168, 85, 247, 0.2)' },
        },
        'flow-down': {
            '0%': { transform: 'translateY(-100%)' },
            '100%': { transform: 'translateY(100%)' },
        },
        'data-stream': {
            '0%': { strokeDashoffset: '100' },
            '100%': { strokeDashoffset: '0' },
        }
      },
    },
  },
  plugins: [],
};
